### PR TITLE
FactionsGUI.java

### PR DESCRIPTION
**Pull request by Beelruce**
I just edited the fonts because I wanted to make it look neater for my server.

### CODE REVIEW

**Comment by BrannonBlair** [comment]
Sounds good!

**Comment by Beelruce** [comment]
Do you know how I can put this in the plugin?

**Comment by BrannonBlair** [comment]
What do you mean?

**Comment by Beelruce** [comment]
How can I compile this source into a plugin so I can use this for my server.

**Comment by BrannonBlair** [comment]
Contact my skype, i'll give you the file: yodamonkey5

**Pull request merged**
